openapi: 3.0.2
# for build full openapi file:
# create one file   -> swagger-cli bundle openapi.yml --outfile _build/openapi.yaml --type yaml
# Swagger Editor    -> https://editor-next.swagger.io/
# start the program -> http://localhost:8082/swagger-ui/index.html
components:
  schemas:
    FraudUser: { $ref: "./schemas/FraudUser.yml" }
info:
  title: fraud user app
  description: "fraud user app description"
  termsOfService: https://editor.swagger.io/ or https://editor-next.swagger.io/
  contact:
    email: example@gmail.com
    url: https://editor-next.swagger.io/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-SNAPSHOT
externalDocs:
  description: Find out more about swagger
  url: https://swagger.io/specification/
servers:
  - url: http://localhost:8082
tags:
  - name: Fraud User
    description: Operations about Fraud user
    externalDocs:
      description: Find out more about our store
      url: https://editor-next.swagger.io/
  - name: Depo Data
paths:
  /users/{id}:
    $ref: "./paths/fraudUsers_id.yml"
  /users:
    $ref: "./paths/fraudUsers.yml"
  /depo-data:
    $ref: "./paths/depoData.yml"
