openapi: 3.0.2
components:
  schemas:
    FraudUser: {$ref: "./schemas/FraudUser.yml" }
info:
  title: fraud user app
  description: "fraud user app description"
  termsOfService: https://editor.swagger.io/ or https://editor-next.swagger.io/
  contact:
    email: example@gmail.com
    url: https://swagger.io/specification/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-SNAPSHOT
externalDocs:
  description: Find out more about swagger
  url: https://swagger.io/specification/
servers:
  - url: http://localhost:8080
tags:
  - name: Fraud User
    description: Operations about Fraud user
    externalDocs:
      description: Find out more about our store
      url: https://editor-next.swagger.io/
paths:
  /fraud_users/{id}:
    $ref: "./paths/fraudUsers_id.yml"
  /fraud_users:
    $ref: "./paths/fraudUsers.yml"
