server:
  port: 8082
  shutdown: graceful

logging.level:
  org.springframework.orm.jpa.JpaTransactionManager: DEBUG

spring:
  main:
    banner-mode: off
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5433/fraud
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    properties.hibernate:
      enable_lazy_load_no_trans: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
